---
execute: 
  enabled: true
bibliography: ref.bib
suppress-bibliography: true
format:
    physmed-revealjs:
        title: My awesome Physmed template presentation with a multiline title
        author: Author name
        supervisors: "Supervisors or other stuff"
        institute: Physics for Medicine Paris, ESPCI Paris, PSL University, Inserm U1273, CNRS UMR 8063
---

## {.center}

::: {style="font-size: 2.5em"}
This is a slide without a title. It has white background and a logo in the top right.
:::


## {.center background-color="#000"}

::: {style="font-size: 2.5em"}
Maybe you want to contrast an awesome ULM image with black background? The logo in the top right is now white.
:::

## Maybe like this? @renaudinFunctionalUltrasoundLocalization2022 {background-color="#000"}

::: {.r-stack}
{{< video https://www.youtube.com/watch?v=gfKZ0JaY-0M width="1700" aspect-ratio="16x9" >}}
:::

## Contents

Some example slides - [also look at example RevealJS slides in the Quarto docs](https://quarto.org/docs/presentations/revealjs/)

* Non-executable and executable code-blocks
* bullet points with highlighting 
* two-column slides 
* how to include a slide from a separate MD file
* preview and link to a webpage

## Just a code block, nothing gets executed...

... but there is some fancy highlighting

```{.python code-line-numbers="1|3|4-9"}
from pathlib import Path

home_path = Path.home()
if home_path.exists():
  data_path = home_path / "data"
else:
  pass
  # raise some error maybe?
```

::: {style="font-size: 2em"}
<p>&nbsp;</p>
<p>&nbsp;</p>
And some cool fragment animations <span class="fragment contour">that contour</span> some words for <span class="fragment contour">emphasys</span>.
:::

## {#final-slide .center background-image=_extensions/physmed/background_swirl.png background-color="#000"}

<h1>Thank you</h1>